// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIO3PidmGQx15jOGm1Ypdk0TBcQFmFR0E',
    appId: '1:98650316812:web:3c89da44e86ced44114e29',
    messagingSenderId: '98650316812',
    projectId: 'flutter-my-app-7a349',
    authDomain: 'flutter-my-app-7a349.firebaseapp.com',
    storageBucket: 'flutter-my-app-7a349.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWRzS_rgu63SMiyGScKN2ForNkldJOdpc',
    appId: '1:98650316812:android:3601c3d82c65d1a1114e29',
    messagingSenderId: '98650316812',
    projectId: 'flutter-my-app-7a349',
    storageBucket: 'flutter-my-app-7a349.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJnk5McCstLVMcHHB_LPGXl6n6xMMxfxM',
    appId: '1:98650316812:ios:a140f4d440d0f7d7114e29',
    messagingSenderId: '98650316812',
    projectId: 'flutter-my-app-7a349',
    storageBucket: 'flutter-my-app-7a349.appspot.com',
    iosClientId: '98650316812-hdc2n7flct7lveee7psm3t0kvihm2juv.apps.googleusercontent.com',
    iosBundleId: 'com.yoooy.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJnk5McCstLVMcHHB_LPGXl6n6xMMxfxM',
    appId: '1:98650316812:ios:61c84945ff56ec1b114e29',
    messagingSenderId: '98650316812',
    projectId: 'flutter-my-app-7a349',
    storageBucket: 'flutter-my-app-7a349.appspot.com',
    iosClientId: '98650316812-ibqkjngaf32c9j01rn9n1r5s4skumqmk.apps.googleusercontent.com',
    iosBundleId: 'com.yoooy.firebase.RunnerTests',
  );
}
